---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# rjts

<!-- badges: start -->
<!-- badges: end -->

The goal of {rjts} is to provide a basic {rJava} wrapper around JTS Topology Suite <<https://www.osgeo.org/projects/jts/>>.

See the Javadoc <<https://locationtech.github.io/jts/javadoc/>> to see the tools that are provided via JTS.

## Installation

You can install the development version of {rjts} thusly:

``` r
# install.packages("remotes")
remotes::install_github("brownag/rjts")
```

## Example

This is an example showing how to read Well-known Text (WKT), perform various basic geometric operations, returning the WKT result.

```{r example}
library(rjts)

wr <- WKTReader()

# read a MULTIPOLYGON from character vector
x <- wr$read("MULTIPOLYGON (((40 40, 20 45, 45 30, 40 40)),
                           ((20 35, 10 30, 10 10, 30 5, 45 20, 20 35),
                           (30 20, 20 15, 20 25, 30 20)))")
x$getGeometryType()

# use the WKTWriter to return Well-known text
ww <- WKTWriter()
ww$writeFormatted(x$convexHull())

## TODO: WKBWriter example

# Geometry objects/results also have a toString() method that returns WKT
x$getBoundary()$toString()
x$convexHull()$toString()
```
